# Generated by Django 3.1.2 on 2020-12-08 20:03

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='entry_text',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
